[project]
name = "receipt-print"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "python-escpos>=3.1",
    "pyusb>=1.3.1",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
receipt-print = "receipt_print.cli:main"

